#server:
#  port: 8888
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#spring:
#  application:
#    name: SpringAPIGateway
#  cloud:
#    gateway:
#      routes:
#      - id: Users
#        uri: http://localhost:8081
#        predicates:
#        - Path=/*
#      - id: TrainInformation
#        uri: http://localhost:8082
#        predicates:
#        - Path=/*
#      - id: Booking
#        uri: http://localhost:8083
#        predicates:
#        - Path=/*
#      
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#              allowedOrigins: "*"
#              allowedMethods: "*"
#              allowedHeaders: "*"